### ISSUE TITLE
Packagist out-of-sync with repo

### ISSUE THREAD

**Issue by mbabker** [FriendsOfSylius/SyliusImportExportPlugin#100]
On Packagist the master branch reports being last updated on March 30 with commit d8b09263dbb4d9be5b66ea73ce86781332e909b5 but there have been several commits since then.

**Comment by stefandoorn** [comment]
0.9.1 also didn't make it to Packagist.

**Comment by mbabker** [comment]
Looks to be addressed, `composer update` on a project this morning updated correctly.
