### ISSUE TITLE
make it possible to use different MQ systems

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSylius/SyliusImportExportPlugin#127]
https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/120 added support for Redis MQ based on the php enqueue library. the code should now be refactored so that any of the supported libraries from enqueue can be used.

**Comment by enesaktay** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/config_reference.md
might be interesting for this issue
