### ISSUE TITLE
setup scrutinizer

### ISSUE THREAD

**Issue by solutionDrive-Alt** [FriendsOfSylius/SyliusImportExportPlugin#13]
_From @lsmith77 on October 28, 2017 19:30_

_Copied from original issue: solutionDrive/SyliusImportExportPlugin#11_

**Comment by lsmith77** [comment]
done .. however still need to be configured 
https://scrutinizer-ci.com/g/FriendsOfSylius/SyliusImportExportPlugin/inspections/69b72c8a-d8b5-4b05-8b32-9edb04e13d5c

see also https://sylius-devs.slack.com/archives/C7H8V410U/p1510051730000450

**Comment by lsmith77** [comment]
fixed
