### ISSUE TITLE
Hide xlsx ans json export button on Sylius Order

### ISSUE THREAD

**Issue by kaizokou** [FriendsOfSylius/SyliusImportExportPlugin#134]
Hello,

How can I hide the xlsx and json buttons ?
<img width="274" alt="screen shot 2018-07-20 at 15 56 06" src="https://user-images.githubusercontent.com/15847039/43009438-9bb49ef6-8c35-11e8-9c11-542d960f1c28.png">

**Comment by enesaktay** [comment]
as a hotfix i'd recommend inserting ```$format = 'csv';``` in line 103 of right above `$parameters = [`
`friendsofsylius/sylius-import-export-plugin/src/Listener/ExportButtonGridListener.php`
this will hardcode it to csv
it is planned to make this bundle configurable. with that change I am pretty sure this will be handled
@lsmith77 ?

**Comment by lsmith77** [comment]
yeah .. we should at some point start adding config options for such things ..

we of course should also add translation strings :)

**Comment by enesaktay** [comment]
the translation strings are perfectly fine for me, so i guess he might need a cache clear?

**Comment by kaizokou** [comment]
@enesaktay thank you, the hotfix is working.

Is there another way than cloning the bundle and add my own version of it in the composer.json ?
Maybe I can override the ExportButtonGridListener in my bundle ?

+1 @lsmith77 for config options, I actually searched the documentation, the code and on internet for quiet a while before asking here, I really though this would already be part of the plugin and that I wasn't able to find it. 

anyway thx guys.

**Comment by 113408** [comment]
@lsmith77  If you can provide some guidance I would be interested in making a PR. Do you see it as new entries on the config, reading them on the `FOSSyliusImportExportExtension` then using the params on `ExportButtonGridListener` ?

**Comment by lsmith77** [comment]
via https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/156 the option should be removed automatically if the relevant lib is not installed.

do you need to be able to configure it per entity type or does this already solve your needs?

**Comment by oallain** [comment]
ping @kaizokou 

> via #156 the option should be removed automatically if the relevant lib is not installed.
> 
> do you need to be able to configure it per entity type or does this already solve your needs?
