### ISSUE TITLE
PhpSpreadsheet

### ISSUE THREAD

**Issue by Minishlink** [FriendsOfSylius/SyliusImportExportPlugin#157]
Hello,

Do you have plans to migrate PHPExcel to [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet)? PHPExcel is marked as deprecated.

**Comment by Minishlink** [comment]
Oops, this project uses https://github.com/portphp/excel so they're the one to notify :)

**Comment by stefandoorn** [comment]
I've seen they started working on it, but it's already for a long time and not finished last time I checked.
