### ISSUE TITLE
Succes Messages but skipped not IMPORTED to DB

### ISSUE THREAD

**Issue by stevangoldduck** [FriendsOfSylius/SyliusImportExportPlugin#159]
It shows success, but no data imported. It shows _Time taken in ms: 0.7, Imported 0, Skipped 1, Failed 0_

**Comment by stefandoorn** [comment]
Found the issue?

**Comment by stevangoldduck** [comment]
yeah i found it, my bad..
we can't give a space too much. Just try upload it as same as the file from _tests/Behat/Resources/fixtures_
