### ISSUE TITLE
build is broken for Sylius 1.2

### ISSUE THREAD

**Issue by solutionDrive-Alt** [FriendsOfSylius/SyliusImportExportPlugin#162]
The build for Sylius 1.2 is broken, since Sylius removed the `PageObject` [here](https://github.com/Sylius/Sylius/pull/9887/files#diff-b60f9c1b17ff4155013ce42e6baa3be4).

**Comment by oallain** [comment]
Hello @solutionDrive-Alt,

All builds are good now.
Do you think we can close this issue?
