### ISSUE TITLE
CSV delimiter different in import and export files

### ISSUE THREAD

**Issue by oallain** [FriendsOfSylius/SyliusImportExportPlugin#171]
Hi,

I think, the fact of the delimiter of the CSV file is semicolon (;) for exports and comma (,) for imports is not logical.

As a result, we can not import a file we just exported :(

I propose to use the comma (,) delimiter for exports.

What do you think ?

**Comment by stefandoorn** [comment]
My preference would be ; for both, but I'm not sure what tools like Excel export generally. Probably best to stay as close as possible to these, as that makes working with imports easier.

**Comment by oallain** [comment]
> Comma separated values text files (.csv), in which the comma character (,) typically separates each field of text.

Read at https://support.office.com/en-us/article/import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba

I'm on Linux so and can't make test now :disappointed:

**Comment by stefandoorn** [comment]
Then it makes sense to stick to a comma, cc @lsmith77 @solutionDrive-Alt.

Would you be able to open a PR with the suggested changes?

**Comment by solutionDrive-Alt** [comment]
I'm totally fine with `comma` as separator.

**Comment by lsmith77** [comment]
yeah, lets go with `comma` by default

**Comment by oallain** [comment]
Hello,

I do PR #172 for fix that :)

**Comment by solutionDrive-Alt** [comment]
fixed by #172

**Comment by oallain** [comment]
Thank you ! :tada:
