### ISSUE TITLE
[Behat] Export links on Countries grid

### ISSUE THREAD

**Issue by oallain** [FriendsOfSylius/SyliusImportExportPlugin#176]
If you run the Behat twice, the tests are in error because the "Export links on Countries Grid" test (in features/export/ui/export_check_ids.feature) checks identifiers that are different for each test (id auto-increment).

**Comment by solutionDrive-Alt** [comment]
yeah, that's a Problem. We should try to avoid asserting fixed ids in our tests, since something like autoincrement can always happen.

**Comment by solutionDrive-Alt** [comment]
@oallain thx for the PR.

**Comment by oallain** [comment]
@solutionDrive-Alt with pleasure :+1:
