### ISSUE TITLE
Custom resource exporter fix, cannot run behat

### ISSUE THREAD

**Issue by caillioux** [FriendsOfSylius/SyliusImportExportPlugin#192]
Hi, I have done some work to fix export button for grids on custom resources but I'm stuck with launching the behat features.

```
$ bin/behat features --tags="~@javascript"
The service "sylius.behat.checker.image_existence" has a dependency on a non-existent parameter "sylius_core.public_dir".  
```

Any clue of what's wrong here?

**Comment by oallain** [comment]
Hello @theyoux ,

Our tests behat, are only compatible up to version 1.3. * of Sylius.

To fix this you can modify in your **composer.json** the line concerning Sylius like this:
`"sylius/sylius": "~1.3.0",`

In order to make tests compatbile with Sylius >= 1.4 we must follow the guide https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.4.md#behat but this is a BC. 

Do you think we should do it? @bitbager  @stefandoorn @solutionDrive-Alt @lsmith77

**Comment by lsmith77** [comment]
yeah .. I guess we need to keep up :-/

**Comment by solutionDrive-Alt** [comment]
I agree, we should keep up to date with later Sylius-Versions. Will we need different versions of the plugin then or is the `latest` behat-configuration backwards-compatible to Sylius < 1.4.x?

**Comment by oallain** [comment]
@solutionDrive-Alt I do not think Behat's configuration is backwards compatible with Sylius < 1.4.x.
FriendsOfBehat / SymfonyExtension has gone into version 2 causing a lot of change.
Nevertheless, I haven't tested, so I'm not sure ;)

**Comment by oallain** [comment]
Ok, well, I tested based on the Sylius/PluginSkeleton for Sylius 1.4 and it works well with our plugin.

> $ bin/behat --strict -vvv --no-interaction features/
> 31 scénarios (31 succès)
> 164 étapes (164 succès)

With Sylius 1.5 i had many errors :
> $ bin/behat --strict -vvv --no-interaction features/
> 31 scénarios (17 succès, 14 échecs)
> 164 étapes (80 succès, 14 échecs, 70 ignorés)

On the other hand, we lose the compatibility with version 1.3 and lower of Sylius.

I developed it quickly, I will do a PR to migrate by making the code a bit cleaner :)

**Comment by oallain** [comment]
I think it's done since https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/193
