### ISSUE TITLE
Adding a csv file with differently named fields

### ISSUE THREAD

**Issue by MaximilianWiesmayr** [FriendsOfSylius/SyliusImportExportPlugin#197]
So I am currently trying to import some data form a CSV-file which contains the same fields, but these fields are named different. I can't change the name of the fields in my CSV-file and I don't want to edit every field by modifiing the Model, because it would be an absolute overkill.

For example: id <-> customer_id.

Is there a solution for this problem implemented in the plugin and if not does someone know a workaround or an alternative?

**Comment by oallain** [comment]
Hello,

I'm not sure if I understood what your need, but if I understood what you're trying to do, there's no way without coding it.

You will have to make the following way:
* Create a Processor, to hydrate your object according to the colones of your csv that you wish
* Use the Processor you created in the Import you want to edit

You have an example with payment methods:
* service processor definition: https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/src/Resources/config/services.yml#L245
* service processor class: https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/src/Processor/PaymentMethodProcessor.php#L14
* service import definition: https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/src/Resources/config/services_import_csv.yml#L34
* you can use the ResourceImporter, you do not need to create the class.

Regards,

**Comment by MaximilianWiesmayr** [comment]
Thanks! 
I didn't realiesed that you can write your own Processor

**Comment by oallain** [comment]
You're welcome
