### ISSUE TITLE
Update "queue-interop/queue-interop" version lock to un-block actual version 0.8

### ISSUE THREAD

**Issue by diimpp** [FriendsOfSylius/SyliusImportExportPlugin#210]
>        "queue-interop/queue-interop": "^0.6.2"

`queue-interop/queue-interop` is locked at ^0.6.2, which means `>=0.6.2  <0.7` for `0.` unstable versioning. So actual `queue-interop` version 0.8 is un-installable. 

I would suggest to upgrade version lock to `^0.6` or `^0.6.2|^0.7|^0.8`

**Comment by oallain** [comment]
Thanks @diimpp !

Fixed by merged #213
