### ISSUE TITLE
Had to modify DateTimeToStringHandler.php to get the plugin working

### ISSUE THREAD

**Issue by Floflinou** [FriendsOfSylius/SyliusImportExportPlugin#211]
I can't get the date to appear while exporting the orders grid, I think something might be wrong with the DateTimeToStringHandler.php file, has anybody experienced that ? I had to modify the __construct argument to array because otherwise I would get a "expected argument of type string array given" error.

Has it happened to anyone else ?

`
```
final class DateTimeToStringHandler extends Handler
{
    /** @var array */
    private $format;

    public function __construct(array $format)
    {
        $this->format = $format;
    }
```
`

I got no answers through Slack, thus why I'm asking here. Thanks in advance

**Comment by oallain** [comment]
Hi @Floflinou 

I couldn't reproduce this error.
If I make the same change as yours, I have a type error.

Can you tell me more ?
The version of PHP and Sylius and the Plugin?
If possible, a technique to reproduce the error.

Thank you

**Comment by Floflinou** [comment]
Hi @oallain 

Actually I made it work, but still the "checkoutCompletedAt" date doesn't appear in the extracted file. Can you please explain briefly how this plugin works so I can find a way around this problem ?

Thank you !

**Comment by oallain** [comment]
Hi @Floflinou 

As you can see in [src/Resources/config/services_export_csv.yml#L23](https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/src/Resources/config/services_export_csv.yml#L23)  Checkout_completed_at shoud be exported, but it may not work yet :( 

For fix it, you need to update [src/Exporter/Plugin/OrderResourcePlugin.php](https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/src/Exporter/Plugin/OrderResourcePlugin.php) and add a line like

`$this->addDataForResource($resource, 'Checkout_completed_at', /** DATE_HERE **/ );`

You can also add test (if possible) in [features/export/cli/exporting_orders_to_csv_via_cli.feature](https://github.com/FriendsOfSylius/SyliusImportExportPlugin/blob/master/features/export/cli/exporting_orders_to_csv_via_cli.feature) 

I hope it will help you.

**Comment by Floflinou** [comment]
Hi @oallain 

I added:

`            $this->addDataForResource($resource, 'Checkout_completed_at', $resource->getCheckoutCompletedAt())`

And it worked like a charm, I have a couple of other empty fields but I think I got it now thanks to you !

Thanks a lot ;)

**Comment by oallain** [comment]
@Floflinou , 
Glad to have helped you.
Do you want to contribute to this project and make a pull request with the patches?

**Comment by Floflinou** [comment]
@oallain 

Yes I’d love to ! How should I do that exactly ? Just by making a pull request and posting the updated file(s) ?

**Comment by oallain** [comment]
@Floflinou 
In summary, if you want to contribute to a project, the simplest way is to:
- Fork project
- Clone it to your local system
- Make a new branch
- Make your changes
- Push it back to your repo
- Click the Compare & pull request button
- Click Create pull request to open a new pull request

You can find more info at https://opensource.com/article/19/7/create-pull-request-github for example.
