### ISSUE TITLE
Support for Symfony 4.4

### ISSUE THREAD

**Issue by andychan94** [FriendsOfSylius/SyliusImportExportPlugin#237]
Plugin does not seem to be compatible with Symfony 4.4.
```
friendsofsylius/sylius-import-export-plugin 0.18.0 requires symfony/stopwatch ^3.3 | ^4.1
```
Symfony 4.4 comes with symfony/stopwatch v5.0.8
Is there a workaround?

**Comment by andychan94** [comment]
I forked the repo and added the version needed to stopwatch and it seems to be working fine
```"symfony/stopwatch": "^3.3 | ^4.1 | ^5.0",```

**Comment by oallain** [comment]
Hi @andychan94 ,

Do you want to make PR here for add it ?
