### ISSUE TITLE
Export data from related columns

### ISSUE THREAD

**Issue by KiseYao** [FriendsOfSylius/SyliusImportExportPlugin#267]
Hello! Any idea how I can export data from table, which has related columns. I've created exporter for my custom entity and it's works good for not related columns. Related columns is empty.

**Comment by redips** [comment]
@ivan-pazhoha I found now your question, how did you solve it? If I've well understood you are capale to export for example the verifiedAt field of user that is linked to the customer via the $user field, is that right? I'm trying to do this: export the verifiedAt of the user when exporting the customers. Please let me/us know how did you do, thank you in advance.
