### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by andriusvo** [FriendsOfSylius/SyliusImportExportPlugin#269]
Is PHP 8.0 support planned for this plugin? Because I can't see nothing breakable here.. Thanks

**Comment by olimination** [comment]
Issue https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/271 has been closed. Worked for me with the latest versions of PHP 8.0.16 and portphp/csv 2.0.1.
