### ISSUE TITLE
Sylius 1.11 and PHP 8 support

### ISSUE THREAD

**Issue by laurentdabbb** [FriendsOfSylius/SyliusImportExportPlugin#273]
Hi and happy new year,

Sylius is near to release 1.11.
With this new version Sylius will no longer support PHP<8.

Do you plan to support PHP 8 and to release a new version compatible with Sylius 1.11 in the near future ?

Thanks in advance for you feedback

**Comment by oallain** [comment]
Hello,

I can't handle it right now.
Regarding PHP 8, there is a solution here: https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/271#issuecomment-1064869060
You can also make a PR to help, it will be very appreciated by all.

Thanks
