### ISSUE TITLE
Composer installs a very old version of the plugin

### ISSUE THREAD

**Issue by manzikki** [FriendsOfSylius/SyliusImportExportPlugin#276]
composer require friendsofsylius/sylius-import-export-plugin

  Problem 1
    - Root composer.json requires friendsofsylius/sylius-import-export-plugin ^0.20.0 -> satisfiable by friendsofsylius/sylius-import-export-plugin[0.20.0].
    - friendsofsylius/sylius-import-export-plugin 0.20.0 requires php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.

**Comment by rimas-kudelis** [comment]
@manzikki a new release has just been tagged, which stopped requiring PHP7 specifically (#277). Do you still have experience this problem?
