### ISSUE TITLE
can export order？

### ISSUE THREAD

**Issue by benyang2015** [FriendsOfSylius/SyliusImportExportPlugin#39]

**Comment by solutionDrive-Alt** [comment]
Not yet, since the #37 is not finished, yet.

**Comment by landsman** [comment]
I want export order too. It will be possible do some custom export with my columns by extending standard export class?

**Comment by solutionDrive-Alt** [comment]
At the moment the export feature is still work-in-progress, so I would not recommend using it at the moment. I hope we can get the PR #37 merged in the next couple of days, but at the moment there are still some details I'm not quite happy with and I want to get right before merging.

But when the feature is ready, every Resource should be exportable quite easily.

**Comment by mbklnd** [comment]
Hi. I've seen PR #37 Looks like it's complete now. Do we have any timeframe for when this will be merged?

**Comment by solutionDrive-Alt** [comment]
Hi @mbklnd , I think we get it merged in the next week or so. I need to find some time to finish the last things. (like updating the README with some more details)
I hope I find time this weekend.

**Comment by solutionDrive-Alt** [comment]
@mbklnd #37 is now merged.

**Comment by mbklnd** [comment]
Brilliant, thanks for the update @solutionDrive-Alt

**Comment by lsmith77** [comment]
closing since the question as answered
