### ISSUE TITLE
make commands services

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSylius/SyliusImportExportPlugin#52]
https://symfony.com/doc/current/console/commands_as_services.html

**Comment by stefandoorn** [comment]
Added PR (#58). Downside is that the exporter command requires the container at this moment to get the proper repository. Probably would be nice to have a command instance that can have the proper repository injected, but that might be next improvement. Not sure if we can do that just with the `services.yml` we currently have (maybe via a factory or smth) or that we need to use compiler passes for it.

**Comment by lsmith77** [comment]
we can use this https://github.com/symfony/symfony/pull/21553

**Comment by stefandoorn** [comment]
How would that look in practice?

**Comment by lsmith77** [comment]
we would inject a service locator service, which would be define dynamically with all the exporter services.

**Comment by lsmith77** [comment]
I created #74 for the switch to service locator
