### ISSUE TITLE
Some dependency broke behat-suite

### ISSUE THREAD

**Issue by solutionDrive-Alt** [FriendsOfSylius/SyliusImportExportPlugin#54]
After updating the composer packages, the behat suite does not run any longer. I also restarted the last successfull build in travis and [the build was broken](https://travis-ci.org/FriendsOfSylius/SyliusImportExportPlugin/jobs/347660392#L909) with the same error.

The error is:

> In ParameterBag.php line 102:
>                                                                                                                                          
>   The service "test.behat.context.cli_countries_context" has a dependency on a non-existent parameter "__symfony__.kernel.project_dir".  
>                                                                                                                                          

The output of the composer update on my machine were:

>  Package operations: 0 installs, 8 updates, 0 removals
>   - Updating twig/twig (v2.4.4 => v2.4.6): Downloading (100%)         
>   - Updating sylius/sylius (v1.1.0 => v1.1.1): Downloading (100%)         
>   - Updating symfony/symfony (v3.4.4 => v3.4.5): Downloading (100%)         
>   - Updating doctrine/orm (v2.6.0 => v2.6.1): Downloading (100%)         
>   - Updating sensiolabs/security-checker (v4.1.7 => v4.1.8): Downloading (100%)         
>   - Updating friendsofsymfony/rest-bundle (2.3.0 => 2.3.1): Downloading (100%)         
>   - Updating slevomat/coding-standard (4.4.6 => 4.5.0): Downloading (100%)         
>   - Updating nikic/php-parser (v3.1.4 => v3.1.5): Downloading (100%)         
>

**Comment by stefandoorn** [comment]
Shouldn't it be `__sylius__.kernel.project_dir` as it's Behat fetching it from the Symfony container?

**Comment by stefandoorn** [comment]
Ah, it already is that:

```
    <parameters>
        <parameter key="behat.files_directory">%__symfony__.kernel.project_dir%/tests/Behat/Resources/fixtures</parameter>
    </parameters>
```

**Comment by lsmith77** [comment]
same here ..
https://travis-ci.org/FriendsOfSylius/SyliusImportExportPlugin/jobs/348897843#L923

**Comment by lsmith77** [comment]
fixed via https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/60
