### ISSUE TITLE
add support for enqueue to support messages queues

### ISSUE THREAD

**Issue by solutionDrive-Alt** [FriendsOfSylius/SyliusImportExportPlugin#8]
_From @lsmith77 on October 28, 2017 19:24_

see also https://github.com/php-enqueue

see for some inspiration https://github.com/Sylake/SyliusConsumerPlugin/tree/master/src

_Copied from original issue: solutionDrive/SyliusImportExportPlugin#5_

**Comment by lsmith77** [comment]
for this we likely will need to decouple the parsing from entity creation.

**Comment by lsmith77** [comment]
also relates to #7

**Comment by solutionDrive-Alt** [comment]
also relates to #30

**Comment by lsmith77** [comment]
https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/120
