### ISSUE TITLE
Cannot install plugin with Sylius 1.1.4

### ISSUE THREAD

**Issue by thomasdom** [FriendsOfSylius/SyliusImportExportPlugin#97]
When doing `composer require friendsofsylius/sylius-import-export-plugin --dev`, composer throw this error:

<img width="1061" alt="capture d ecran 2018-04-11 a 10 27 58" src="https://user-images.githubusercontent.com/12234140/38605348-54a17a36-3d73-11e8-9afd-20d38679acea.png">

It seems that this plugin conflicts with Symfony 3.4.5+, which is required by Sylius 1.1.4 (symfony/symfony locked at 3.4.8), but I don't know why.

**Comment by stefandoorn** [comment]
Can you try for now with Sylius 1.1.3 and a little lower Symfony version? There is some issues with Sylius 1.1.3 & 1.1.4 (1.1.5 should be released somewhere these days). So in the upcoming days this issue should be resolved, but for now this should do it.

**Comment by thomasdom** [comment]
Ok, I'll try this. Thank you for your quick reply!
